ENG-29 プロトタイプ実装
3O-Inc/company_hp pull request #9
Opened 2023-10-08 03:35 UTC by yuyasugi

## やったこと
* プロトタイプ実装
## やらないこと
* 実際の内容入力
## 課題

## できるようになること（ユーザ目線）

## できなくなること（ユーザ目線）

## 動作確認

## その他
![screencapture-localhost-3000-2023-10-08-12_32_42](https://github.com/3O-Inc/company_hp/assets/94780281/28d29ddd-cbb5-4bda-a509-959d77f64873)

2023-10-08 07:13 UTC, tatsu081 reviewed
レビューしたので、また確認お願いします！！！

2023-10-08 07:13 UTC, tatsu081 commented on src/app/components/AboutUs.tsx
componentの設計をこちらの記事を参考に変更をお願いします！
今回の場合だと、`components/layouts/AboutUs.tsx`とするのがいいかなと感じました！
→この方が今後の修正するときにまとめやすいと思いました！

※もし何かご意見あれば、色々とおっしゃって下さい😄

↓参考記事
https://zenn.dev/yodaka/articles/eca2d4bf552aeb

2023-10-08 07:13 UTC, tatsu081 commented on src/app/components/Footer.tsx
こちらも`AboutUs.tsx`同様に変更をお願いします🙇‍♂️

2023-10-08 07:13 UTC, tatsu081 commented on src/app/components/Header.tsx
こちらもAboutUs.tsx同様に変更をお願いします🙇‍♂️

2023-10-08 07:13 UTC, tatsu081 commented on src/app/components/Member.tsx
こちらも`AboutUs.tsx`同様に変更をお願いします🙇‍♂️

2023-10-08 07:13 UTC, tatsu081 commented on src/app/components/Header.tsx
> +        <Text as="a" href="#about-us" fontWeight="bold" p={1} fontSize="lg" color="black" ml={4}>
こちら同様のものになると思うので、HeaderのButtonをcomponent化していきましょう！！！！
`以下記事を参考にしながら、/components/elements`にButtonのcomponentを作成すると良いかと思いました！

https://zenn.dev/yodaka/articles/eca2d4bf552aeb

2023-10-08 07:14 UTC, tatsu081 requested changes
レビューしました！！
ご確認お願いします🙇‍♂️

もし共通化できそうな部分あれば、なるべく共通化することをお願いします！

2023-10-09 07:09 UTC, tatsu081 reviewed
レビューしたので確認お願いします！

2023-10-09 07:09 UTC, tatsu081 commented on src/app/components/elememts/Button/HeaderLink.tsx
命名規則的に`HeaderLinkButton.tsx`の方がファイル名がいいです！！！

2023-10-09 07:09 UTC, tatsu081 commented on src/app/components/elememts/Button/HeaderLink.tsx
> +export const HeaderLink: React.FC<HeaderLinkProps> = ({ label, href }) => {
ここも`HeaderLinkButton`に変更をお願いします！

2023-10-09 07:09 UTC, tatsu081 commented on src/app/components/index.tsx
ここのファイルってchakra-uiで一般的に設定されてるものですかね？？？

2023-10-12 11:40 UTC, yuyasugi commented on src/app/components/index.tsx
@tatsu081 
一般的には設定されていないかもしれないです！
下記記事を参考にして、この箇所は実装してみました。
Chakra UIのコンポーネントを使うたびに毎回use clientを宣言するのは手間なので、一箇所にまとめておこうという意図があります！

https://zenn.dev/azukiazusa/articles/next-js-app-dir-tutorial#:~:text=Chakra%20UI%20%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%82%92%E4%BD%BF%E3%81%86%E3%81%9F%E3%81%B3%E3%81%AB%20%22use%20client%22%20%E3%82%92%E5%AE%A3%E8%A8%80%E3%81%99%E3%82%8B%E3%81%AE%E3%81%AF%E6%89%8B%E9%96%93%E3%81%8C%E3%81%8B%E3%81%8B%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82app/common/components/index.tsx%20%E3%81%A7%E3%81%BE%E3%81%A8%E3%82%81%E3%81%A6%20Chatra%20UI%20%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%82%92%20export%20%E3%81%97%E3%81%A6%20Client%20Component%20%E3%81%A8%E3%81%97%E3%81%A6%E4%BD%BF%E3%81%88%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%81%BE%E3%81%99%E3%80%82

2023-10-17 10:52 UTC, tatsu081 approved these changes
LGTM

2023-10-17 10:53 UTC, merged